### ISSUE TITLE
Counting down timer

### ISSUE THREAD

**Issue by putupradnya** [astarica/jasmine#23]
fitur hitung mundur hari pernikahan

![image](https://user-images.githubusercontent.com/25524439/118152793-4c3df400-b43f-11eb-8d22-26790f751cf2.png)

**Comment by mwafa** [comment]
Bikin di adobe xd nya tu,

**Comment by putupradnya** [comment]
> Bikin di adobe xd nya tu,

Oke, baru mau di desain
