### ISSUE TITLE
Gift Page

### ISSUE THREAD

**Issue by putupradnya** [astarica/jasmine#37]
Tambahan: 

- [x] Intro sebelum minta duit
- [x] Tambah form reservasi

tambah dibagian setelah maps dan sebelum protokol
bikin form simple aja kali yaa 
![image](https://user-images.githubusercontent.com/25524439/120113835-82e96d80-c1a6-11eb-8139-a4a836bb20bd.png)

**Comment by mwafa** [comment]
Form simple nya gimana? Apa aja konten nya?

**Comment by putupradnya** [comment]
> Form simple nya gimana? Apa aja konten nya?

selengkapnya: [disini](https://www.figma.com/file/PqgwN5uVUJttLoHhbne4jA/Dashboard?node-id=0%3A1)
![image](https://user-images.githubusercontent.com/25524439/120960434-077b5380-c786-11eb-94a4-e0704fe88622.png)

**Comment by mwafa** [comment]
Dengan mengurangi rasa hormat .... @astarica

**Comment by astarica** [comment]
> Tambahan:
> 
> * [ ]  Intro sebelum minta duit
> * [x]  Tambah form reservasi
> 
> tambah dibagian setelah maps dan sebelum protokol
> bikin form simple aja kali yaa
> ![image](https://user-images.githubusercontent.com/25524439/120113835-82e96d80-c1a6-11eb-8139-a4a836bb20bd.png)

Tanpa mengurangi rasa hormat, bagi anda yang ingin memberi tanda kasih untuk pengantin, dapat melalui
